### PR TITLE
add dockerfile to run Flask

### PR DESCRIPTION
**Pull request by maye-msft**
- add dockerfile to run Flask
- push to dockerhub
- add run with docker in README
- add docker pull image in README
- change the default url from /static/index.html to index.html

### CODE REVIEW

**Review by thurstonchen — COMMENTED** [review]
Hi Sean,

Just pulled this feature branch and updated the /.devcontainer/devcontainer.json file to point to the new Dockerfile instead, and the index.html page looks good after the dev-container is up and running, then shall we merge those two Dockerfiles? Many thanks!

Best,
Thurston

**Comment by gary918** [comment]
> 

I'm thinking the same, @thurstonchen :).

**Comment by maye-msft** [comment]
> Hi Sean,
> 
> Just pulled this feature branch and updated the /.devcontainer/devcontainer.json file to point to the new Dockerfile instead, and the index.html page looks good after the dev-container is up and running, then shall we merge those two Dockerfiles? Many thanks!
> 
> Best, Thurston

As you know, I have changed the dev container to use the Dockerfile in src folder
Sean

**Review by thurstonchen — APPROVED** [review]

**Review by gary918 — APPROVED** [review]
Thank you @maye-msft for making the container environment complete.

**Pull request merged**
